language: python

cache:
  directories:
    - $HOME/.cache/pip

env:
    global:
        - DEPENDS=cython
        - INSTALL_TYPE="setup"
        - MANYLINUX_URL=https://nipy.bic.berkeley.edu/manylinux

python:
    - 2.6
    - 3.2
    - 3.3
    - 3.4
    - 3.5

matrix:
  include:
    - python: 2.7
      env:
        - INSTALL_TYPE=sdist
    - python: 2.7
      env:
        - INSTALL_TYPE=wheel
    - python: 2.7
      # Check minimum dependency
      env:
        # Check CYTHON_MIN_VERSION in setup.py
        - DEPENDS=cython==0.18

before_install:
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python -m pip install -U pip wheel
    - pip install -f $MANYLINUX_URL $DEPENDS

install:
    - |
      if [ "$INSTALL_TYPE" == "setup" ]; then
          python setup.py install
      elif [ "$INSTALL_TYPE" == "sdist" ]; then
          python setup.py egg_info  # check egg_info while we're here
          python setup.py sdist
          # Check install from sdist works without Cython
          cd dist
          pip uninstall -y cython
          pip install --pre --no-index -f . x86cpu
          cd ..
      elif [ "$INSTALL_TYPE" == "wheel" ]; then
          pip install wheel
          python setup.py bdist_wheel
          pip install dist/*.whl
      fi

script:
    - pip install pytest
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - py.test --pyargs x86cpu
    # Test script output
    - x86report
