# vim ft=yaml
# CI on Windows via appveyor
# Largely from:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

os: Visual Studio 2015

environment:

    global:
      WHEELHOUSE_UPLOADER_USERNAME: matthew.brett
      WHEELHOUSE_UPLOADER_SECRET:
        secure:
            wSarKWZqmNbc3fTkBlUtt1h4zPxjqy4/Brv0df/guuOsce47ojjISbFph1LMPT0b

    matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - python -m pip install --upgrade pip
  # Pin wheel to 0.26 to avoid Windows ABI tag for built wheel
  - pip install wheel==0.26
  - pip install cython pytest

build_script:
  # Fix MSVC builds for 64-bit Python
  # See
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"
  # Build and install
  - python setup.py bdist_wheel
  - pip install --pre --no-index -f .\dist x86cpu
  - ps: |
      # Upload artifact to Appveyor immediately after build
      ls dist -r | Foreach-Object {
          appveyor PushArtifact $_.FullName
          pip install $_.FullName
          }

test_script:
  # Run the project tests
  - py.test x86cpu

on_success:
  # Deploy only for tags:
  # http://www.appveyor.com/docs/deployment#deploy-on-tag-github-only
  # on:
  #  branch: master
  #  appveyor_repo_tag: true
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  # - pip install wheelhouse-uploader
  # - python -m wheelhouse_uploader upload --no-ssl-check --local-folder=dist win-dev-wheels
